PrefabFiles = {
	"df_berrybush",
	"df_debug_label",
    "df_driftwood",
	"df_fog",
	"df_grass",
	"df_mushroom",
	"df_reeds",
	"df_rock_water",
	"df_waterspot",
	"df_pan",
	"df_mosquito",
	"df_poison_ivy",
	"eviltree_tall",
	"scyther",
	"waterfall_oceanevil",
	"df_unassuming_tree",
}