return {
  version = "1.10",
  luaversion = "5.1",
  tiledversion = "1.10.2",
  class = "",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 4,
  height = 4,
  tilewidth = 64,
  tileheight = 64,
  nextlayerid = 3,
  nextobjectid = 27,
  properties = {},
  tilesets = {
    {
      name = "Don't Starve Together Terrains",
      firstgid = 1,
      filename = "../../../../../../Don't Starve Mod Tools/mod_tools/Tiled/DST Tileset/Don't Starve Together Terrains.tsx"
    }
  },
  layers = {
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 4,
      height = 4,
      id = 1,
      name = "BG_TILES",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      encoding = "lua",
      data = {
        0, 0, 0, 0,
        0, 0, 0, 0,
        0, 0, 0, 0,
        0, 0, 0, 0
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 2,
      name = "FG_OBJECTS",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 1,
          name = "skeleton",
          type = "skeleton",
          shape = "rectangle",
          x = 108.413,
          y = 106.094,
          width = 38.7435,
          height = 38.0591,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 11,
          name = "df_poison_ivy",
          type = "df_poison_ivy",
          shape = "rectangle",
          x = 151.327,
          y = 87.0969,
          width = 15.469,
          height = 16.4778,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 12,
          name = "df_poison_ivy",
          type = "df_poison_ivy",
          shape = "rectangle",
          x = 121.734,
          y = 60.867,
          width = 22.5309,
          height = 20.1769,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 13,
          name = "df_grass",
          type = "df_grass",
          shape = "rectangle",
          x = 165.787,
          y = 47.0794,
          width = 24.5486,
          height = 29.9291,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 14,
          name = "df_poison_ivy",
          type = "df_poison_ivy",
          shape = "rectangle",
          x = 85.7518,
          y = 48.0883,
          width = 25.8937,
          height = 28.5839,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 15,
          name = "df_poison_ivy",
          type = "df_poison_ivy",
          shape = "rectangle",
          x = 73.6457,
          y = 84.0704,
          width = 21.1857,
          height = 23.876,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 16,
          name = "df_grass",
          type = "df_grass",
          shape = "rectangle",
          x = 184.619,
          y = 105.929,
          width = 24.8848,
          height = 26.23,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 17,
          name = "df_poison_ivy",
          type = "df_poison_ivy",
          shape = "rectangle",
          x = 156.035,
          y = 129.468,
          width = 16.8141,
          height = 17.4866,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 18,
          name = "df_grass",
          type = "df_grass",
          shape = "rectangle",
          x = 133.168,
          y = 162.76,
          width = 32.9556,
          height = 31.9468,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 19,
          name = "df_grass",
          type = "df_grass",
          shape = "rectangle",
          x = 186.3,
          y = 153.008,
          width = 31.2742,
          height = 34.3007,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 20,
          name = "df_grass",
          type = "df_grass",
          shape = "rectangle",
          x = 73.982,
          y = 154.69,
          width = 27.5751,
          height = 31.9468,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 21,
          name = "df_grass",
          type = "df_grass",
          shape = "rectangle",
          x = 49.4334,
          y = 115.008,
          width = 39.6812,
          height = 35.6459,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 22,
          name = "df_poison_ivy",
          type = "df_poison_ivy",
          shape = "rectangle",
          x = 55.8228,
          y = 69.9466,
          width = 13.4513,
          height = 17.8229,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 23,
          name = "df_grass",
          type = "df_grass",
          shape = "rectangle",
          x = 36.3184,
          y = 47.0794,
          width = 15.8052,
          height = 20.8495,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 24,
          name = "df_grass",
          type = "df_grass",
          shape = "rectangle",
          x = 97.5217,
          y = 198.742,
          width = 21.1857,
          height = 22.8672,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 25,
          name = "df_grass",
          type = "df_grass",
          shape = "rectangle",
          x = 49.7697,
          y = 181.592,
          width = 21.1857,
          height = 23.5397,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 26,
          name = "df_grass",
          type = "df_grass",
          shape = "rectangle",
          x = 167.132,
          y = 194.035,
          width = 25.5574,
          height = 25.8937,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    }
  }
}
