return {
  version = "1.10",
  luaversion = "5.1",
  tiledversion = "1.10.2",
  class = "",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 8,
  height = 8,
  tilewidth = 64,
  tileheight = 64,
  nextlayerid = 3,
  nextobjectid = 101,
  properties = {},
  tilesets = {
    {
      name = "Don't Starve Together Terrains",
      firstgid = 1,
      filename = "../../../../../../Don't Starve Mod Tools/mod_tools/Tiled/DST Tileset/Don't Starve Together Terrains.tsx"
    }
  },
  layers = {
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 8,
      height = 8,
      id = 1,
      name = "BG_TILES",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      encoding = "lua",
      data = {
        0, 0, 0, 0, 0, 0, 0, 0,
        0, 139, 139, 139, 139, 139, 139, 0,
        0, 139, 139, 139, 139, 139, 139, 0,
        0, 139, 139, 139, 139, 139, 139, 0,
        0, 139, 139, 139, 139, 139, 139, 0,
        0, 139, 139, 139, 139, 139, 139, 0,
        0, 139, 139, 139, 139, 139, 139, 0,
        0, 0, 0, 0, 0, 0, 0, 0
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 2,
      name = "FG_OBJECTS",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 28,
          name = "gravestone",
          type = "gravestone",
          shape = "rectangle",
          x = 128,
          y = 128,
          width = 39.3333,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 35,
          name = "gravestone",
          type = "gravestone",
          shape = "rectangle",
          x = 128,
          y = 256,
          width = 39.3333,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 36,
          name = "gravestone",
          type = "gravestone",
          shape = "rectangle",
          x = 128,
          y = 384,
          width = 39.3333,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 29,
          name = "gravestone",
          type = "gravestone",
          shape = "rectangle",
          x = 192,
          y = 128,
          width = 39.3333,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 34,
          name = "gravestone",
          type = "gravestone",
          shape = "rectangle",
          x = 192,
          y = 256,
          width = 39.3333,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 37,
          name = "gravestone",
          type = "gravestone",
          shape = "rectangle",
          x = 192,
          y = 384,
          width = 39.3333,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 30,
          name = "gravestone",
          type = "gravestone",
          shape = "rectangle",
          x = 320,
          y = 128,
          width = 39.3333,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 33,
          name = "gravestone",
          type = "gravestone",
          shape = "rectangle",
          x = 320,
          y = 256,
          width = 39.3333,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 39,
          name = "gravestone",
          type = "gravestone",
          shape = "rectangle",
          x = 320,
          y = 384,
          width = 39.3333,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 31,
          name = "gravestone",
          type = "gravestone",
          shape = "rectangle",
          x = 256,
          y = 128,
          width = 39.3333,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 32,
          name = "gravestone",
          type = "gravestone",
          shape = "rectangle",
          x = 256,
          y = 256,
          width = 39.3333,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 38,
          name = "gravestone",
          type = "gravestone",
          shape = "rectangle",
          x = 256,
          y = 384,
          width = 39.3333,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 40,
          name = "flower_evil",
          type = "flower_evil",
          shape = "rectangle",
          x = 356,
          y = 174.667,
          width = 22,
          height = 22.6667,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 97,
          name = "flower_evil",
          type = "flower_evil",
          shape = "rectangle",
          x = 410.667,
          y = 73.3333,
          width = 22,
          height = 22.6667,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 41,
          name = "flower_evil",
          type = "flower_evil",
          shape = "rectangle",
          x = 291.333,
          y = 180.667,
          width = 20.6667,
          height = 18,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 42,
          name = "flower_evil",
          type = "flower_evil",
          shape = "rectangle",
          x = 227.333,
          y = 178.667,
          width = 20,
          height = 19.3333,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 43,
          name = "flower_evil",
          type = "flower_evil",
          shape = "rectangle",
          x = 162,
          y = 182,
          width = 22.6667,
          height = 18.6667,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 44,
          name = "flower_evil",
          type = "flower_evil",
          shape = "rectangle",
          x = 106.667,
          y = 178,
          width = 26.6667,
          height = 22,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 98,
          name = "flower_evil",
          type = "flower_evil",
          shape = "rectangle",
          x = 73.3333,
          y = 74,
          width = 26.6667,
          height = 22,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 45,
          name = "flower_evil",
          type = "flower_evil",
          shape = "rectangle",
          x = 362,
          y = 310.667,
          width = 33.3333,
          height = 25.3333,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 46,
          name = "flower_evil",
          type = "flower_evil",
          shape = "rectangle",
          x = 300,
          y = 315.333,
          width = 30.6667,
          height = 20,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 47,
          name = "flower_evil",
          type = "flower_evil",
          shape = "rectangle",
          x = 240,
          y = 313.333,
          width = 32,
          height = 23.3333,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 48,
          name = "flower_evil",
          type = "flower_evil",
          shape = "rectangle",
          x = 187.333,
          y = 308,
          width = 24.6667,
          height = 22,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 49,
          name = "flower_evil",
          type = "flower_evil",
          shape = "rectangle",
          x = 112.667,
          y = 313.333,
          width = 28,
          height = 22,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 50,
          name = "flower_evil",
          type = "flower_evil",
          shape = "rectangle",
          x = 376.667,
          y = 432.667,
          width = 20.6667,
          height = 20.6667,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 51,
          name = "flower_evil",
          type = "flower_evil",
          shape = "rectangle",
          x = 302,
          y = 442,
          width = 18.6667,
          height = 20.6667,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 52,
          name = "flower_evil",
          type = "flower_evil",
          shape = "rectangle",
          x = 246.667,
          y = 442,
          width = 18.6667,
          height = 20.6667,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 53,
          name = "flower_evil",
          type = "flower_evil",
          shape = "rectangle",
          x = 183.333,
          y = 440,
          width = 24.6667,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 54,
          name = "flower_evil",
          type = "flower_evil",
          shape = "rectangle",
          x = 106.667,
          y = 442.667,
          width = 28.6667,
          height = 20.6667,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 55,
          name = "wall_stone",
          type = "wall_stone",
          shape = "rectangle",
          x = 448.667,
          y = 98.6667,
          width = 28,
          height = 28.6667,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 83,
          name = "wall_stone",
          type = "wall_stone",
          shape = "rectangle",
          x = 449.333,
          y = 132.667,
          width = 28,
          height = 28.6667,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 84,
          name = "wall_stone",
          type = "wall_stone",
          shape = "rectangle",
          x = 449.333,
          y = 166,
          width = 28,
          height = 28.6667,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 85,
          name = "wall_stone",
          type = "wall_stone",
          shape = "rectangle",
          x = 450,
          y = 196,
          width = 28,
          height = 28.6667,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 86,
          name = "wall_stone",
          type = "wall_stone",
          shape = "rectangle",
          x = 449.333,
          y = 230,
          width = 28,
          height = 28.6667,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 87,
          name = "wall_stone",
          type = "wall_stone",
          shape = "rectangle",
          x = 448.667,
          y = 260,
          width = 28,
          height = 28.6667,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 88,
          name = "wall_stone",
          type = "wall_stone",
          shape = "rectangle",
          x = 448.667,
          y = 292.667,
          width = 28,
          height = 28.6667,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 89,
          name = "wall_stone",
          type = "wall_stone",
          shape = "rectangle",
          x = 447.333,
          y = 322,
          width = 28,
          height = 28.6667,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 90,
          name = "wall_stone",
          type = "wall_stone",
          shape = "rectangle",
          x = 448.667,
          y = 356.667,
          width = 28,
          height = 28.6667,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 91,
          name = "wall_stone",
          type = "wall_stone",
          shape = "rectangle",
          x = 448.667,
          y = 387.333,
          width = 28,
          height = 28.6667,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 92,
          name = "wall_stone",
          type = "wall_stone",
          shape = "rectangle",
          x = 448.667,
          y = 420,
          width = 28,
          height = 28.6667,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 93,
          name = "wall_stone",
          type = "wall_stone",
          shape = "rectangle",
          x = 448,
          y = 450.667,
          width = 28,
          height = 28.6667,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 94,
          name = "wall_stone",
          type = "wall_stone",
          shape = "rectangle",
          x = 418,
          y = 452,
          width = 28,
          height = 28.6667,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 56,
          name = "wall_stone",
          type = "wall_stone",
          shape = "rectangle",
          x = 449.333,
          y = 69.3333,
          width = 28,
          height = 28.6667,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 57,
          name = "wall_stone",
          type = "wall_stone",
          shape = "rectangle",
          x = 449.333,
          y = 38.6667,
          width = 28,
          height = 28.6667,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 58,
          name = "wall_stone",
          type = "wall_stone",
          shape = "rectangle",
          x = 419.333,
          y = 37.3333,
          width = 28,
          height = 28.6667,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 59,
          name = "wall_stone",
          type = "wall_stone",
          shape = "rectangle",
          x = 387.333,
          y = 37.3333,
          width = 28,
          height = 28.6667,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 60,
          name = "wall_stone",
          type = "wall_stone",
          shape = "rectangle",
          x = 354,
          y = 36.6667,
          width = 28,
          height = 28.6667,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 61,
          name = "wall_stone",
          type = "wall_stone",
          shape = "rectangle",
          x = 320.667,
          y = 36.6667,
          width = 28,
          height = 28.6667,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 62,
          name = "wall_stone",
          type = "wall_stone",
          shape = "rectangle",
          x = 288.667,
          y = 36,
          width = 28,
          height = 28.6667,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 63,
          name = "wall_stone",
          type = "wall_stone",
          shape = "rectangle",
          x = 257.333,
          y = 36,
          width = 28,
          height = 28.6667,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 64,
          name = "wall_stone",
          type = "wall_stone",
          shape = "rectangle",
          x = 226,
          y = 36,
          width = 28,
          height = 28.6667,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 65,
          name = "wall_stone",
          type = "wall_stone",
          shape = "rectangle",
          x = 193.333,
          y = 36,
          width = 28,
          height = 28.6667,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 66,
          name = "wall_stone",
          type = "wall_stone",
          shape = "rectangle",
          x = 160.667,
          y = 36,
          width = 28,
          height = 28.6667,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 67,
          name = "wall_stone",
          type = "wall_stone",
          shape = "rectangle",
          x = 129.333,
          y = 36,
          width = 28,
          height = 28.6667,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 68,
          name = "wall_stone",
          type = "wall_stone",
          shape = "rectangle",
          x = 98,
          y = 36.6667,
          width = 28,
          height = 28.6667,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 69,
          name = "wall_stone",
          type = "wall_stone",
          shape = "rectangle",
          x = 65.3333,
          y = 35.3333,
          width = 28,
          height = 28.6667,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 70,
          name = "wall_stone",
          type = "wall_stone",
          shape = "rectangle",
          x = 34.6667,
          y = 36,
          width = 28,
          height = 28.6667,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 71,
          name = "wall_stone",
          type = "wall_stone",
          shape = "rectangle",
          x = 34,
          y = 70,
          width = 28,
          height = 28.6667,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 72,
          name = "wall_stone",
          type = "wall_stone",
          shape = "rectangle",
          x = 35.3333,
          y = 101.333,
          width = 28,
          height = 28.6667,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 73,
          name = "wall_stone",
          type = "wall_stone",
          shape = "rectangle",
          x = 35.3333,
          y = 129.333,
          width = 28,
          height = 28.6667,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 74,
          name = "wall_stone",
          type = "wall_stone",
          shape = "rectangle",
          x = 34.6667,
          y = 162.667,
          width = 28,
          height = 28.6667,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 75,
          name = "wall_stone",
          type = "wall_stone",
          shape = "rectangle",
          x = 35.3333,
          y = 194.667,
          width = 28,
          height = 28.6667,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 76,
          name = "wall_stone",
          type = "wall_stone",
          shape = "rectangle",
          x = 34.6667,
          y = 228.667,
          width = 28,
          height = 28.6667,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 77,
          name = "wall_stone",
          type = "wall_stone",
          shape = "rectangle",
          x = 35.3333,
          y = 261.333,
          width = 28,
          height = 28.6667,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 78,
          name = "wall_stone",
          type = "wall_stone",
          shape = "rectangle",
          x = 35.3333,
          y = 293.333,
          width = 28,
          height = 28.6667,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 79,
          name = "wall_stone",
          type = "wall_stone",
          shape = "rectangle",
          x = 36,
          y = 326.667,
          width = 28,
          height = 28.6667,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 80,
          name = "wall_stone",
          type = "wall_stone",
          shape = "rectangle",
          x = 34,
          y = 361.333,
          width = 28,
          height = 28.6667,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 81,
          name = "wall_stone",
          type = "wall_stone",
          shape = "rectangle",
          x = 35.3333,
          y = 390.667,
          width = 28,
          height = 28.6667,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 82,
          name = "wall_stone",
          type = "wall_stone",
          shape = "rectangle",
          x = 33.3333,
          y = 420.667,
          width = 28,
          height = 28.6667,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 95,
          name = "wall_stone",
          type = "wall_stone",
          shape = "rectangle",
          x = 33.3333,
          y = 450,
          width = 28,
          height = 28.6667,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 96,
          name = "wall_stone",
          type = "wall_stone",
          shape = "rectangle",
          x = 66,
          y = 452,
          width = 28,
          height = 28.6667,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 99,
          name = "placeholder2",
          type = "goldnugget",
          shape = "rectangle",
          x = 328,
          y = 72.6667,
          width = 40.6667,
          height = 36,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 100,
          name = "placeholder",
          type = "goldnugget",
          shape = "rectangle",
          x = 132.667,
          y = 70.6667,
          width = 48,
          height = 39.3333,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    }
  }
}
