local NAMES = STRINGS.NAMES
local RECIPE_DESC = STRINGS.RECIPE_DESC
local ANNOUNCE = STRINGS.CHARACTERS.GENERIC
local DESCRIBE = STRINGS.CHARACTERS.GENERIC.DESCRIBE

--- Other
DESCRIBE.TURF_EVILFOREST = "It's a creepy tuft of grass"
NAMES.TURF_EVILFOREST = "DarkForest Turf"

NAMES.HIDDEN_IN_DF_FOG = "???"
ANNOUNCE.DESCRIBE_HIDDEN_IN_DF_FOG = "Did you see that? I didn't."

---	Recipes
RECIPE_DESC.TURF_EVILFOREST = "A patch of disturbing grass."